
export const iconDependencies = [
{ icon: 'access', extensions: ['accdb', 'accdt', 'mdb', 'accda', 'accdc', 'accde', 'accdp', 'accdr', 'accdu', 'ade', 'adp', 'laccdb', 'ldb', 'mam', 'maq', 'mdw']},
{ icon: 'actionscript', extensions: [] },
{ icon: 'ai', extensions: ['ai'] },
{ icon: 'ai2', extensions: ['ai'],  disabled: true },
{ icon: 'org', extensions: ['org'] },
{ icon: 'angular', extensions: ['angular-cli.json', 'angular-cli.json'],  },
{ icon: 'ng_component_ts', extensions: ['component.ts'],  disabled: true },
{ icon: 'ng_component_js', extensions: ['component.js'],  disabled: true },
{ icon: 'ng_controller_ts', extensions: ['controller.ts'],  disabled: true },
{ icon: 'ng_controller_js', extensions: ['controller.js'],  disabled: true },
{ icon: 'ng_directive_ts', extensions: ['directive.ts'],  disabled: true },
{ icon: 'ng_directive_js', extensions: ['directive.js'],  disabled: true },
{ icon: 'ng_guard_ts', extensions: ['guard.ts'],  disabled: true },
{ icon: 'ng_guard_js', extensions: ['guard.js'],  disabled: true },
{ icon: 'ng_module_ts', extensions: ['module.ts'],  disabled: true },
{ icon: 'ng_module_js', extensions: ['module.js'],  disabled: true },
{ icon: 'ng_pipe_ts', extensions: ['pipe.ts'],  disabled: true },
{ icon: 'ng_pipe_js', extensions: ['pipe.js'],  disabled: true },
{ icon: 'ng_routing_ts', extensions: ['routing.ts'],  disabled: true },
{ icon: 'ng_routing_js', extensions: ['routing.js'],  disabled: true },
{ icon: 'ng_routing_ts', extensions: ['app-routing.module.ts'],   disabled: true },
{ icon: 'ng_routing_js', extensions: ['app-routing.module.js'],   disabled: true },
{ icon: 'ng_smart_component_ts', extensions: ['page.ts', 'container.ts'],  disabled: true },
{ icon: 'ng_smart_component_js', extensions: ['page.js', 'container.js'],  disabled: true },
{ icon: 'ng_service_ts', extensions: ['service.ts'],  disabled: true },
{ icon: 'ng_service_js', extensions: ['service.js'],  disabled: true },
{ icon: 'ng_component_ts2', extensions: ['component.ts'],  disabled: true },
{ icon: 'ng_component_js2', extensions: ['component.js'],  disabled: true },
{ icon: 'ng_directive_ts2', extensions: ['directive.ts'],  disabled: true },
{ icon: 'ng_directive_js2', extensions: ['directive.js'],  disabled: true },
{ icon: 'ng_module_ts2', extensions: ['module.ts'],  disabled: true },
{ icon: 'ng_module_js2', extensions: ['module.js'],  disabled: true },
{ icon: 'ng_pipe_ts2', extensions: ['pipe.ts'],  disabled: true },
{ icon: 'ng_pipe_js2', extensions: ['pipe.js'],  disabled: true },
{ icon: 'ng_routing_ts2', extensions: ['routing.ts'],  disabled: true },
{ icon: 'ng_routing_js2', extensions: ['routing.js'],  disabled: true },
{ icon: 'ng_routing_ts2', extensions: ['app-routing.module.ts'],   disabled: true },
{ icon: 'ng_routing_js2', extensions: ['app-routing.module.js'],   disabled: true },
{ icon: 'ng_smart_component_ts2', extensions: ['page.ts', 'container.ts'],  disabled: true },
{ icon: 'ng_smart_component_js2', extensions: ['page.js', 'container.js'],  disabled: true },
{ icon: 'ng_service_ts2', extensions: ['service.ts'],  disabled: true },
{ icon: 'ng_service_js2', extensions: ['service.js'],  disabled: true },
{ icon: 'ansible', extensions: [] },
{ icon: 'anyscript', extensions: [] },
{ icon: 'apache', extensions: [] },
{ icon: 'apib', extensions: [] },
{ icon: 'applescript', extensions: [] },
{ icon: 'appveyor', extensions: ['appveyor.yml', 'appveyor.yml'],  },
{ icon: 'asp', extensions: [] },
{ icon: 'aspx', extensions: ['aspx', 'ascx'] },
{ icon: 'assembly', extensions: [] },
{ // https://en.wikipedia.org/wiki/Audio_file_format
    icon: 'audio',
    extensions: ['aac', 'act', 'aiff', 'amr', 'ape', 'au', 'dct', 'dss', 'dvf', 'flac', 'gsm',
    'iklax', 'ivs', 'm4a', 'm4b', 'm4p', 'mmf', 'mogg', 'mp3', 'mpc', 'msv', 'oga', 'ogg', 'opus',
    'ra', 'raw', 'tta', 'vox', 'wav', 'wma'],
    
},
{ icon: 'aurelia', extensions: ['aurelia.json'],  },
{ icon: 'autohotkey', extensions: [] },
{ icon: 'autoit', extensions: [] },
{ icon: 'aws', extensions: [] },
{ icon: 'babel', extensions: ['babelrc'],  },
{ icon: 'bat', extensions: [] },
{ // http://www.file-extensions.org/filetype/extension/name/binary-files
    icon: 'binary',
    extensions: ['a', 'app', 'bin', 'cmo', 'cmx', 'cma', 'cmxa', 'cmi', 'dll', 'exe', 'hl', 'ilk',
    'lib', 'n', 'ndll', 'o', 'obj', 'pyc', 'pyd', 'pyo', 'pdb', 'scpt', 'scptd', 'so'],
    
},
{ icon: 'bithound', extensions: ['bithoundrc'],  },
{ icon: 'blade', extensions: [] },
{ icon: 'bolt', extensions: [],  },
{ icon: 'bower', extensions: ['bowerrc', 'bower.json'],  },
{ icon: 'buckbuild', extensions: ['buckconfig'],  },
{ icon: 'bundler', extensions: ['gemfile', 'gemfile.lock'],  },
{ icon: 'c', extensions: ['c'] },
{ icon: 'c2', extensions: [],  disabled: true },
{ icon: 'cabal', extensions: [] },
{ icon: 'cake', extensions: [] },
{ icon: 'cakephp', extensions: [] },
{ icon: 'cf', extensions: ['lucee'] },
{ icon: 'cf2', extensions: ['lucee'],  disabled: true },
{ icon: 'cfc', extensions: [] },
{ icon: 'cfc2', extensions: [],  disabled: true },
{ icon: 'cfm', extensions: [] },
{ icon: 'cfm2', extensions: [],  disabled: true },
{ icon: 'cheader', extensions: ['h'] },
{ icon: 'chef', extensions: ['chefignore', 'berksfile', 'berksfile.lock', 'policyfile'],  },
{ icon: 'class', extensions: ['class'] },
{ icon: 'circleci', extensions: ['circle.yml'], light: true,  },
{ icon: 'clojure', extensions: ['cjm', 'cljc'] },
{ icon: 'cmake', extensions: [] },
{ icon: 'cobol', extensions: [] },
{ icon: 'codeclimate', extensions: ['codeclimate.yml'], light: true,  },
{ icon: 'codecov', extensions: ['codecov.yml', 'codecov.yml'],  },
{ icon: 'codekit', extensions: ['kit'] },
{ icon: 'codekit', extensions: ['config.codekit', 'config.codekit2', 'config.codekit3'],  },
{ icon: 'coffeescript', extensions: [] },
{ icon: 'config', extensions: ['env'], light: true },
{ icon: 'config', extensions: ['env.example'], light: true,  },
{ icon: 'compass', extensions: [] },
{ icon: 'composer', extensions: ['composer.json', 'composer.lock'],  },
{ icon: 'cpp', extensions: [] },
{ icon: 'cpp2', extensions: ['cpp'],  disabled: true },
{ icon: 'cppheader', extensions: ['hpp'] },
{ icon: 'crystal', extensions: [] },
{ icon: 'csharp', extensions: ['csx', 'cs'] },
{ icon: 'csproj', extensions: ['csproj'] },
{ icon: 'css', extensions: ['css'] },
{ icon: 'csslint', extensions: ['csslintrc'],  },
{ icon: 'cssmap', extensions: ['css.map'] },
{ icon: 'cucumber', extensions: [] },
{ icon: 'dartlang', extensions: [] },
{ icon: 'delphi', extensions: [] },
{ icon: 'dlang', extensions: [] },
{ icon: 'diff', extensions: [] },
{ icon: 'docker', extensions: ['dockerignore', 'docker-compose.yml', 'docker-compose.ci-build.yml', 'docker-compose.override.yml', 'docker-compose.vs.debug.yml', 'docker-compose.vs.release.yml', 'docker-cloud.yml'] },
{ icon: 'docker2', extensions: ['dockerignore', 'docker-compose.yml', 'docker-compose.ci-build.yml', 'docker-compose.override.yml', 'docker-compose.vs.debug.yml', 'docker-compose.vs.release.yml', 'docker-cloud.yml'], disabled: true },
{ icon: 'drone', extensions: ['drone.yml', 'drone.yml.sig'], light: true,  },
{ icon: 'editorconfig', extensions: ['editorconfig'],  },
{ icon: 'ejs', extensions: ['ejs'] },
{ icon: 'elasticbeanstalk', extensions: [] },
{ icon: 'elixir', extensions: [] },
{ icon: 'elm', extensions: ['elm-package.json'], },
{ icon: 'elm2', extensions: ['elm-package.json'], disabled: true },
{ icon: 'emacs', extensions: ['el', 'elc'] },
{ icon: 'ember', extensions: ['ember-cli'],  },
{ icon: 'ensime', extensions: ['ensime'] },
{ icon: 'eps', extensions: ['eps'] },
{ icon: 'erb', extensions: [] },
{ icon: 'erlang', extensions: ['emakefile', 'emakerfile'] },
{ icon: 'eslint', extensions: ['eslintrc', 'eslintignore', 'eslintrc.js', 'eslintrc.json', 'eslintrc.yaml', 'eslintrc.yml'],  },
{ icon: 'eslint2', extensions: ['eslintrc', 'eslintignore', 'eslintrc.js', 'eslintrc.json', 'eslintrc.yaml', 'eslintrc.yml'],   disabled: true },
{ icon: 'excel', extensions: ['xls', 'xlsx', 'xlsm', 'ods'] },
{ icon: 'favicon', extensions: ['favicon.ico'],  },
{ icon: 'firebase', extensions: ['firebaserc'],  },
{ icon: 'flash', extensions: ['swf', 'swc'] },
{ icon: 'flow', extensions: ['js.flow'] },
{ icon: 'flow', extensions: ['flowconfig'],  },
{ icon: 'font', extensions: ['woff', 'woff2', 'ttf', 'otf', 'eot', 'pfa', 'pfb', 'sfd'], light: true },
{ icon: 'fortran', extensions: [] },
{ icon: 'fsharp', extensions: [] },
{ icon: 'fsproj', extensions: ['fsproj'] },
{ icon: 'freemarker', extensions: [] },
{ icon: 'fusebox', extensions: ['fuse.js'],  },
{ icon: 'git', extensions: ['gitattributes', 'gitconfig', 'gitignore', 'gitmodules', 'gitkeep'] },
{ icon: 'gamemaker', extensions: ['gmx'] },
{ icon: 'gamemaker2', extensions: ['yy', 'yyp'], light: true },
{ icon: 'gamemaker81', extensions: [] },
{ icon: 'gitlab', extensions: ['gitlab-ci.yml'],  },
{ icon: 'glsl', extensions: [] },
{ icon: 'go', extensions: [] },
{ icon: 'godot', extensions: [] },
{ icon: 'gradle', extensions: ['gradle'] },
{ icon: 'graphql', extensions: ['gqlconfig'] },
{ icon: 'graphviz', extensions: [] },
{ icon: 'groovy', extensions: [] },
{ icon: 'groovy2', extensions: [],  disabled: true },
{
    icon: 'grunt', extensions: [
    'gruntfile.coffee',
    'gruntfile.babel.coffee',
    'gruntfile.js',
    'gruntfile.babel.js',
    'gruntfile.ts',
    'gruntfile.babel.ts',
    ],
    
},
{
    icon: 'gulp', extensions: [
    'gulpfile.coffee',
    'gulpfile.babel.coffee',
    'gulpfile.js',
    'gulpfile.babel.js',
    'gulpfile.ts',
    'gulpfile.babel.ts',
    ],
    
},
{ icon: 'haml', extensions: [] },
{ icon: 'handlebars', extensions: [] },
{ icon: 'handlebars2', extensions: [],  disabled: true },
{ icon: 'harbour', extensions: [] },
{ icon: 'haskell', extensions: [] },
{ icon: 'haskell2', extensions: [],  disabled: true },
{ icon: 'haxe', extensions: ['haxelib.json'] },
{ icon: 'haxecheckstyle', extensions: ['checkstyle.json'],  },
{ icon: 'haxedevelop', extensions: ['hxproj'] },
{ icon: 'hlsl', extensions: [] },
{ icon: 'html', extensions: ["html"] },
{ icon: 'idris', extensions: ['idr', 'lidr'] },
{ icon: 'idrisbin', extensions: ['ibc'] },
{ icon: 'idrispkg', extensions: ['ipkg'] },
{ icon: 'image', extensions: ['jpeg', 'jpg', 'gif', 'png', 'bmp', 'tiff', 'ico', 'PNG'] },
{ icon: 'ini', extensions: [], light: true },
{ icon: 'infopath', extensions: ['infopathxml', 'xsn', 'xsf', 'xtp2'] },
{ icon: 'ionic', extensions: ['ionic.project', 'ionic.config.json'],  },
{ icon: 'jar', extensions: ['jar'] },
{ icon: 'java', extensions: ["java"] },
{ icon: 'jbuilder', extensions: ['jbuilder'] },
{ icon: 'jenkins', extensions: ['jenkinsfile'],  },
{ icon: 'jest', extensions: ['jest.config.js', 'jest.json', 'jest.config.json', 'jestrc'],  },
{ icon: 'jinja', extensions: [] },
{ icon: 'js', extensions: ["js"] },
{ icon: 'js_official', extensions: [],  disabled: true },
{ icon: 'jsconfig', extensions: ['jsconfig.json'],  },
{ icon: 'jshint', extensions: ['jshintrc', 'jshintignore'],  },
{ icon: 'jsmap', extensions: ['js.map'] },
{ icon: 'json', extensions: ['json'] },
{ icon: 'json_official', extensions: [],  disabled: true },
{ icon: 'json2', extensions: [],  disabled: true },
{ icon: 'jsonld', extensions: ['jsonld', 'json-ld'], light: true },
{ icon: 'jsp', extensions: ['jsp'] },
{ icon: 'julia', extensions: [] },
{ icon: 'julia2', extensions: [],  disabled: true },
{ icon: 'karma', extensions: ['karma.conf.js', 'karma.conf.coffee'],  },
{ icon: 'kitchenci', extensions: ['kitchen.yml'],  },
{ icon: 'kotlin', extensions: [] },
{ icon: 'layout', extensions: ['master', 'layout.html', 'layout.htm'] },
{ icon: 'layout', extensions: ['layout.html', 'layout.htm'],  },
{ icon: 'lerna', extensions: ['lerna.json'], light: true,  },
{ icon: 'less', extensions: [] },
{ icon: 'license', extensions: ['enc'] },
{ icon: 'license', extensions: ['license', 'licence', 'license.md', 'licence.md', 'license.txt', 'licence.txt'],  },
{ icon: 'lisp', extensions: [] },
{ icon: 'lime', extensions: ['hxp'] },
{ icon: 'lime', extensions: ['include.xml'],  },
{ icon: 'liquid', extensions: ['liquid'] },
{ icon: 'locale', extensions: [] },
{ icon: 'log', extensions: ['log'] },
{ icon: 'lsl', extensions: ['lsl'] },
{ icon: 'lua', extensions: [] },
{ icon: 'lync', extensions: ['crec', 'ocrec'] },
{ icon: 'makefile', extensions: ['makefile'] },
{ icon: 'makefile', extensions: [] },
{ icon: 'map', extensions: ['map'] },
{ icon: 'markdown', extensions: ['mdown', 'markdown'] },
{ icon: 'marko', extensions: [] },
{ icon: 'markojs', extensions: ['marko.js'] },
{ icon: 'matlab', extensions: ['fig', 'mex', 'mexn', 'mexrs6', 'mn', 'mum', 'mx', 'mx3', 'rwd', 'slx', 'slddc', 'smv', 'tikz', 'xvc']},
{ icon: 'meteor', extensions: [] },
{ icon: 'mjml', extensions: [] },
{ icon: 'mustache', extensions: ['mustache', 'mst'], light: true },
{ icon: 'nim', extensions: [] },
{ icon: 'njsproj', extensions: ['njsproj'] },
{ icon: 'node', extensions: ['nvmrc'],  },
{ icon: 'node2', extensions: [],  disabled: true },
{ icon: 'npm', extensions: ['npmignore', 'npmrc', 'package.json', 'package-lock.json'],  },
{ icon: 'nsi', extensions: [] },
{ icon: 'nuget', extensions: ['nupkg', 'nuspec', 'psmdcp'] },
{ icon: 'nunjucks', extensions: ['nunj', 'njs'] },
{ icon: 'objectivec', extensions: [] },
{ icon: 'objectivecpp', extensions: [] },
{ icon: 'ocaml', extensions: ['merlin'] },
{ icon: 'onenote', extensions: ['one', 'onepkg', 'onetoc', 'onetoc2', 'sig'] },
{ icon: 'opencl', extensions: ['cl', 'opencl'] },
{ icon: 'outlook', extensions: ['pst', 'bcmx', 'otm', 'msg', 'oft'] },
{ icon: 'package', extensions: ['pkg'] },
{ icon: 'paket', extensions: ['paket.dependencies', 'paket.lock', 'paket.references', 'paket.template', 'paket.local'],  },
{ icon: 'patch', extensions: ['patch'] },
{ icon: 'pcl', extensions: ['pcd'], light: true },
{ icon: 'pdf', extensions: ['pdf'] },
{ icon: 'pdf2', extensions: ['pdf'],  disabled: true },
{ icon: 'perl', extensions: [] },
{ icon: 'perl2', extensions: [],  disabled: true },
{ icon: 'photoshop', extensions: ['psd'] },
{ icon: 'photoshop2', extensions: ['psd'],  disabled: true },
{ icon: 'php', extensions: ['php1', 'php2', 'php3', 'php4', 'php5', 'php6', 'phps', 'phpsa', 'phpt', 'phtml', 'phar', 'php'] },
{ icon: 'php2', extensions: ['php1', 'php2', 'php3', 'php4', 'php5', 'php6', 'phps', 'phpsa', 'phpt', 'phtml', 'phar'],  disabled: true },
{ icon: 'phpunit', extensions: ['phpunit', 'phpunit.xml', 'phpunit.xml.dist'],  },
{ icon: 'plantuml', extensions: ['pu', 'plantuml', 'iuml', 'puml'] },
{ icon: 'plsql', extensions: [] },
{ icon: 'plsql_package', extensions: ['pck'] },
{ icon: 'plsql_package_body', extensions: ['pkb'] },
{ icon: 'plsql_package_header', extensions: ['pkh'] },
{ icon: 'plsql_package_spec', extensions: ['pks'] },
{ icon: 'poedit', extensions: ['po', 'mo'] },
{ icon: 'polymer', extensions: [] },
{ icon: 'postcss', extensions: ['postcssrc.js', 'postcss.config.js'] },
{ icon: 'powerpoint', extensions: ['pot', 'potx', 'potm', 'pps', 'ppsx', 'ppsm', 'ppt', 'pptx', 'pptm', 'pa', 'ppa', 'ppam', 'sldm', 'sldx'] },
{ icon: 'powershell', extensions: [] },
{ icon: 'procfile', extensions: ['procfile'],  },
{ icon: 'prolog', extensions: ['pro', 'P'] },
{ icon: 'protobuf', extensions: [] },
{ icon: 'protractor', extensions: ['protractor.conf.js'],  },
{ icon: 'publisher', extensions: ['pub', 'puz'] },
{ icon: 'puppet', extensions: [] },
{ icon: 'pug', extensions: ['jade-lintrc', 'pug-lintrc', 'jade-lint.json', 'pug-lintrc.js', 'pug-lintrc.json'] },
{ icon: 'purescript', extensions: [], light: true },
{ icon: 'python', extensions: ['py', 'py3'] },
{ icon: 'qlikview', extensions: ['qvd', 'qvw'] },
{ icon: 'r', extensions: [] },
{ icon: 'rails', extensions: [] },
{ icon: 'rake', extensions: ['rake'] },
{ icon: 'rake', extensions: ['rakefile'],  },
{ icon: 'raml', extensions: [] },
{ icon: 'razor', extensions: [] },
{ icon: 'reactjs', extensions: [] },
{ icon: 'reacttemplate', extensions: ['rt'] },
{ icon: 'reactts', extensions: [] },
{ icon: 'reason', extensions: [] },
{ icon: 'rest', extensions: [] },
{ icon: 'registry', extensions: ['reg'] },
{ icon: 'riot', extensions: [] },
{ icon: 'robotframework', extensions: [] },
{ icon: 'rollup', extensions: ['rollup.config.js', 'rollup.config.ts'],  },
{ icon: 'rspec', extensions: ['rspec'],  },
{ icon: 'ruby', extensions: [] },
{ icon: 'rust', extensions: [] },
{ icon: 'saltstack', extensions: ['sls'] },
{ icon: 'sass', extensions: ['sass'] },
{ icon: 'sbt', extensions: [] },
{ icon: 'scala', extensions: [] },
{ icon: 'script', extensions: [] },
{ icon: 'scss', extensions: ['scss'] },
{ icon: 'sequelize', extensions: ['sequelizerc'],  },
{ icon: 'shaderlab', extensions: [], light: true },
{ icon: 'shell', extensions: ['fish'] },
{ icon: 'slim', extensions: [] },
{ icon: 'sln', extensions: ['sln'] },
{ icon: 'smarty', extensions: [] },
{ icon: 'snyk', extensions: ['snyk'],  },
{ icon: 'solidity', extensions: [], light: true },
{ icon: 'source', extensions: [] },
{ icon: 'sqf', extensions: [] },
{ icon: 'sql', extensions: ['sql'] },
{ icon: 'sqlite', extensions: ['sqlite', 'sqlite3', 'db3'] },
{ icon: 'sss', extensions: ['sss'] },
{ icon: 'style', extensions: [] },
{ icon: 'stylelint', extensions: ['stylelintrc', 'stylelint.config.js', 'stylelintignore'], light: true,  },
{ icon: 'stylus', extensions: [] },
{ icon: 'storyboard', extensions: ['storyboard'] },
{ icon: 'svg', extensions: ['svg'] },
{ icon: 'swagger', extensions: [] },
{ icon: 'swift', extensions: ['package.pins'] },
{ icon: 'tcl', extensions: ['tcl', 'exp'] },
{ icon: 'terraform', extensions: ['tfstate'] },
{ icon: 'test', extensions: ['tst'] },
{ icon: 'testjs', extensions: ['test.js', 'spec.js', 'test.jsx', 'spec.jsx'] },
{ icon: 'testts', extensions: ['test.ts', 'test.tsx', 'spec.ts', 'spec.tsx'] },
{ icon: 'tex', extensions: ['texi'], light: true },
{ icon: 'text', extensions: ['csv',"txt"] },
{ icon: 'textile', extensions: [] },
{ icon: 'tfs', extensions: ['tfignore'],  },
{ icon: 'todo', extensions: ['todo'], light: true },
{ icon: 'toml', extensions: [] },
{ icon: 'travis', extensions: ['travis.yml'],  },
{ icon: 'tsconfig', extensions: ['tsconfig.json', 'tsconfig.app.json', 'tsconfig.spec.json', 'tsconfig.e2e.json'],  },
{ icon: 'tslint', extensions: ['tslint.json'],  },
{ icon: 'twig', extensions: [] },
{ icon: 'typescript', extensions: [] },
{ icon: 'typescript_official', extensions: ['ts'],  disabled: true },
{ icon: 'typescriptdef', extensions: ['d.ts'] },
{ icon: 'typescriptdef_official', extensions: ['d.ts'],  disabled: true },
{ icon: 'vagrant', extensions: ['vagrantfile'],  },
{ icon: 'vash', extensions: ['vash'] },
{ icon: 'vb', extensions: [] },
{ icon: 'vbhtml', extensions: ['vbhtml'] },
{ icon: 'vbproj', extensions: ['vbproj'] },
{ icon: 'vcxproj', extensions: ['vcxproj'] },
{ icon: 'vhdl', extensions: [] },
{ // https://en.wikipedia.org/wiki/Video_file_format
    icon: 'video',
    extensions: ['3g2', '3gp', 'asf', 'amv', 'avi', 'divx', 'qt', 'f4a', 'f4b', 'f4p', 'f4v', 'flv',
    'm2v', 'm4v', 'mkv', 'mk3d', 'mov', 'mp2', 'mp4', 'mpe', 'mpeg', 'mpeg2', 'mpg', 'mpv', 'nsv',
    'ogv', 'rm', 'rmvb', 'svi', 'vob', 'webm', 'wmv'],
    
},
{ icon: 'view', extensions: [] },
{ icon: 'vim', extensions: ['vimrc', 'gvimrc'] },
{ icon: 'volt', extensions: [] },
{
    icon: 'vscode',
    extensions: [
    'vscodeignore.json',
    'launch.json',
    'tasks.json',
    'vscodeignore',
    ],
    
    
},
{ icon: 'vsix', extensions: ['vsix'], light: true },
{ icon: 'vue', extensions: [] },
{ icon: 'watchmanconfig', extensions: ['watchmanconfig'],  },
{
    icon: 'webpack',
    extensions: [
    'webpack.base.conf.coffee',
    'webpack.base.conf.js',
    'webpack.base.conf.ts',
    'webpack.common.coffee',
    'webpack.common.js',
    'webpack.common.ts',
    'webpack.config.coffee',
    'webpack.config.base.coffee',
    'webpack.config.common.coffee',
    'webpack.config.dev.coffee',
    'webpack.config.development.coffee',
    'webpack.config.staging.coffee',
    'webpack.config.test.coffee',
    'webpack.config.prod.coffee',
    'webpack.config.production.coffee',
    'webpack.config.js',
    'webpack.config.base.js',
    'webpack.config.common.js',
    'webpack.config.dev.js',
    'webpack.config.development.js',
    'webpack.config.staging.js',
    'webpack.config.test.js',
    'webpack.config.prod.js',
    'webpack.config.production.js',
    'webpack.config.ts',
    'webpack.config.base.ts',
    'webpack.config.common.ts',
    'webpack.config.dev.ts',
    'webpack.config.development.ts',
    'webpack.config.staging.ts',
    'webpack.config.test.ts',
    'webpack.config.prod.ts',
    'webpack.config.production.ts',
    'webpack.config.babel.js',
    'webpack.config.base.babel.js',
    'webpack.config.common.babel.js',
    'webpack.config.dev.babel.js',
    'webpack.config.development.babel.js',
    'webpack.config.staging.babel.js',
    'webpack.config.test.babel.js',
    'webpack.config.prod.babel.js',
    'webpack.config.production.babel.js',
    'webpack.dev.coffee',
    'webpack.dev.js',
    'webpack.dev.ts',
    'webpack.dev.conf.coffee',
    'webpack.dev.conf.js',
    'webpack.dev.conf.ts',
    'webpack.prod.coffee',
    'webpack.prod.js',
    'webpack.prod.ts',
    'webpack.prod.conf.coffee',
    'webpack.prod.conf.js',
    'webpack.prod.conf.ts',
    'webpack.mix.coffee',
    'webpack.mix.js',
    'webpack.mix.ts',
    'webpack.test.conf.coffee',
    'webpack.test.conf.js',
    'webpack.test.conf.ts',
    ],
    
    
},
{ icon: 'wercker', extensions: ['wercker.yml'],  },
{ icon: 'word', extensions: ['doc', 'docx', 'docm', 'dot', 'dotx', 'dotm', 'wll'] },
{ icon: 'wxml', extensions: ['wxml'] },
{ icon: 'wxss', extensions: ['wxss'] },
{ icon: 'xcode', extensions: ['xcodeproj'] },
{ icon: 'xib', extensions: ['xib'] },
{ icon: 'xliff', extensions: ['xliff', 'xlf'] },
{ icon: 'xml', extensions: ['pex', 'tmlanguage'] },
{ icon: 'xsl', extensions: [] },
{ icon: 'yaml', extensions: ['yml'] },
{ icon: 'yang', extensions: [] },
{ icon: 'yarn', extensions: ['yarn.lock', 'yarnrc', 'yarnclean', 'yarn-integrity', 'yarn-metadata.json', 'yarnignore'],  },
{ icon: 'zip', extensions: ['zip', 'rar', '7z', 'tar', 'gz', 'bzip2', 'xz', 'bz2'] },
{ icon: 'zip2', extensions: ['zip', 'rar', '7z', 'tar', 'gz', 'bzip2', 'xz', 'bz2'],  disabled: true },
];

